const tempData = [
    {
        "employer_name": "Apex Systems, Inc.",
        "employer_logo": "https://www.apexsystems.com/profiles/apex/themes/apex_bootstrap/images/Apex_logo_horizontal_color.png",
        "employer_website": "http://www.apexsystems.com",
        "employer_company_type": "Staffing",
        "job_publisher": "Professional Diversity Network",
        "job_id": "rEVBw2FHnBUAAAAAAAAAAA==",
        "job_employment_type": "CONTRACTOR",
        "job_title": "React Developer",
        "job_apply_link": "https://www.prodivnet.com/job/react-developer-bentonville-arkansas-13450963",
        "job_apply_is_direct": false,
        "job_apply_quality_score": 0.5684,
        "job_description": "Apex Systems is looking for a React Developer to join a Fortune 100 team. Please send your resume to Connor Rynn if you are interested in applying. crynn@apexsystems.com\n\nRequired Experience :\n• 6+ years experience with ReactJS\n• React Context API / useContext (React hook)\n• Typescript experience - not JavaScript\n• Jest and react testing library - important because developers write unit and integration tests.\n• Experience building responsive applications\n• CSS/styling\n\nNice to have experience:\n• NextJS=\n• GraphQL\n\nEEO Employer\n\nApex Systems is an equal opportunity employer. We do not discriminate or allow discrimination on the basis of race, color, religion, creed, sex (including pregnancy, childbirth, breastfeeding, or related medical conditions), age, sexual orientation, gender identity, national origin, ancestry, citizenship, genetic information, registered domestic partner status, marital status, disability, status as a crime victim, protected veteran status, political affiliation, union membership, or any other characteristic protected by law. Apex will consider qualified applicants with criminal histories in a manner consistent with the requirements of applicable law. If you have visited our website in search of information on employment opportunities or to apply for a position, and you require an accommodation in using our website for a search or application, please contact our Employee Services Department at employeeservices@apexsystems.com or 844-463-6178.\n\nVEVRAA Federal Contractor\nWe request Priority Protected Veteran & Disabled Referrals for all of our locations within the state.\nWe are an equal opportunity employer. We evaluate qualified applicants without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, disability, veteran status, or any other protected characteristic. The EEO is the Law poster is available here.\nPDN-99f44f9b-fb2a-4494-bf52-ac681e918e57",
        "job_is_remote": false,
        "job_posted_at_timestamp": 1692776251,
        "job_posted_at_datetime_utc": "2023-08-23T07:37:31.000Z",
        "job_city": "Bentonville",
        "job_state": "AR",
        "job_country": "US",
        "job_latitude": 36.372356,
        "job_longitude": -94.21021,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=rEVBw2FHnBUAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": "2023-11-21T08:37:31.000Z",
        "job_offer_expiration_timestamp": 1700555851,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": 72,
            "experience_mentioned": true,
            "experience_preferred": false
        },
        "job_required_skills": null,
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": false,
            "degree_mentioned": false,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {
            "Qualifications": [
                "6+ years experience with ReactJS",
                "React Context API / use",
                "Typescript experience - not JavaScript",
                "Jest and react testing library - important because developers write unit and integration tests",
                "Experience building responsive applications"
            ]
        },
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15113400",
        "job_onet_job_zone": "3",
        "job_naics_code": "561311",
        "job_naics_name": "Employment Placement Agencies"
    },
    {
        "employer_name": "Upwork",
        "employer_logo": "https://image.status.io/z6aeO6kAGsAG.png",
        "employer_website": "http://www.elance.com",
        "employer_company_type": "Computer Services",
        "job_publisher": "Upwork",
        "job_id": "0YM7KUSZudQAAAAAAAAAAA==",
        "job_employment_type": "CONTRACTOR",
        "job_title": "React Developer Needed - Contract to Hire",
        "job_apply_link": "https://www.upwork.com/freelance-jobs/apply/React-Developer-Needed_~01728b1bd2094c5f0d/",
        "job_apply_is_direct": true,
        "job_apply_quality_score": 0.6816,
        "job_description": "We are creating an innovative digital web based software application to rethink the energy use cycle from top to bottom. The plan is to programmatically with the help of AI and a little luck blood sweat and joyful tears to understand where someone is coming from from a personal standpoint, measure there energy use, understand what revenues are available to them to meet this energy need, and hopefully uncover energy vampires in their existing system to banish.",
        "job_is_remote": true,
        "job_posted_at_timestamp": 1692818663,
        "job_posted_at_datetime_utc": "2023-08-23T19:24:23.000Z",
        "job_city": null,
        "job_state": null,
        "job_country": "US",
        "job_latitude": 37.09024,
        "job_longitude": -95.71289,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=0YM7KUSZudQAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": null,
        "job_offer_expiration_timestamp": null,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": null,
            "experience_mentioned": false,
            "experience_preferred": false
        },
        "job_required_skills": [
            "React",
            "JavaScript",
            "Web Development",
            "Web Application"
        ],
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": false,
            "degree_mentioned": false,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": 70,
        "job_max_salary": 90,
        "job_salary_currency": "USD",
        "job_salary_period": "HOUR",
        "job_highlights": {},
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15113400",
        "job_onet_job_zone": "3",
        "job_naics_code": "541511",
        "job_naics_name": "Custom Computer Programming Services"
    },
    {
        "employer_name": "Horizon Cloud",
        "employer_logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQp45kzrjMeOgQs8l4RORMa_bkE5mI8MbFLfSJM&s=0",
        "employer_website": null,
        "employer_company_type": null,
        "job_publisher": "LinkedIn",
        "job_id": "pT9BDVfGpCMAAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "React Developer",
        "job_apply_link": "https://www.linkedin.com/jobs/view/react-developer-at-horizon-cloud-3693007451",
        "job_apply_is_direct": false,
        "job_apply_quality_score": 0.5831,
        "job_description": "We are looking for a passionate and dedicated React Developer to join our dynamic team. If you have a deep commitment to innovative web application development and love working with the latest frontend technologies, this role is for you.\n\nKey Responsibilities:\n\n- Develop and maintain cutting-edge web applications using React.\n\n- Collaborate with product teams and UI/UX designers to create user-friendly interfaces.\n\n- Write reusable, maintainable, and efficient code.\n\n- Integrate applications with RESTful APIs and handle data fetching.\n\n- Optimize applications for speed and scalability.\n\n- Contribute to the team's processes and strategies with ideas and solutions.\n\nBasic Qualifications:\n\n- Bachelor's degree in Computer Science, Web Development, or a related field (or equivalent work experience).\n\n- Minimum of 2 years of professional experience in web application development with React.\n\n- Strong portfolio showcasing your React projects.\n\n- Solid knowledge of JavaScript, ES6+, HTML5, and CSS3.\n\n- Proven experience with RESTful APIs and asynchronous programming.\n\n- Proficiency with Git or other version control systems.\n\n- Familiarity with front-end build tools such as Webpack, Babel, npm/yarn.\n\n- Comfortable working in an Agile/Scrum development environment.\n\n- Excellent problem-solving skills, attention to detail, and an analytical mindset.\n\n- Strong communication skills, with an ability to collaborate effectively within a team.\n\nPreferred Qualifications:\n\n- Experience with state management libraries such as Redux or Mobx, and component styling frameworks like Styled Components or CSS Modules.\n\n- Up-to-date with modern front-end development trends and techniques.\n\n- Familiarity with testing tools like Jest, Enzyme, and React Testing Library.\n\n- Hands-on experience with responsive and mobile-first design approaches.\n\n- Active participation in open-source projects or personal coding endeavors.\n\nBenefits:\n\n- 401K with Company Match\n\n- 15 Days PTO\n\n- 100% Covered Company Health\n\n- Dental and Vision Insurance\n\n- Company Holidays\n\n- Remote Work\n\nIf you believe you are a fit for this position and are keen on being part of a dynamic, forward-thinking team, please apply with your resume and a link to your portfolio.\n\nHorizon Cloud is an equal opportunity employer. We celebrate diversity and are committed to creating an inclusive environment for all employees.",
        "job_is_remote": true,
        "job_posted_at_timestamp": 1692714126,
        "job_posted_at_datetime_utc": "2023-08-22T14:22:06.000Z",
        "job_city": null,
        "job_state": null,
        "job_country": "US",
        "job_latitude": 37.09024,
        "job_longitude": -95.71289,
        "job_benefits": [
            "dental_coverage",
            "health_insurance",
            "paid_time_off",
            "retirement_savings"
        ],
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=pT9BDVfGpCMAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": "2024-02-18T14:18:07.000Z",
        "job_offer_expiration_timestamp": 1708265887,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": 24,
            "experience_mentioned": true,
            "experience_preferred": false
        },
        "job_required_skills": [
            "styled-components",
            "Babel.js",
            "Skill Development",
            "Control Systems",
            "Employee Benefits",
            "React.js",
            "Build Tools",
            "Remote Work",
            "Web Application Development",
            "Testing Tools"
        ],
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": true,
            "degree_mentioned": true,
            "degree_preferred": true,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {
            "Qualifications": [
                "Bachelor's degree in Computer Science, Web Development, or a related field (or equivalent work experience)",
                "Minimum of 2 years of professional experience in web application development with React",
                "Strong portfolio showcasing your React projects",
                "Solid knowledge of JavaScript, ES6+, HTML5, and CSS3",
                "Proven experience with RESTful APIs and asynchronous programming",
                "Proficiency with Git or other version control systems",
                "Familiarity with front-end build tools such as Webpack, Babel, npm/yarn",
                "Comfortable working in an Agile/Scrum development environment",
                "Excellent problem-solving skills, attention to detail, and an analytical mindset",
                "Strong communication skills, with an ability to collaborate effectively within a team"
            ],
            "Responsibilities": [
                "Develop and maintain cutting-edge web applications using React",
                "Collaborate with product teams and UI/UX designers to create user-friendly interfaces",
                "Write reusable, maintainable, and efficient code",
                "Integrate applications with RESTful APIs and handle data fetching",
                "Optimize applications for speed and scalability",
                "Contribute to the team's processes and strategies with ideas and solutions"
            ],
            "Benefits": [
                "401K with Company Match",
                "15 Days PTO",
                "100% Covered Company Health",
                "Dental and Vision Insurance",
                "Company Holidays",
                "Remote Work"
            ]
        },
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15113400",
        "job_onet_job_zone": "3"
    },
    {
        "employer_name": "developrec",
        "employer_logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxFyp3Xr4mYCk_UvvfkLGDbt9nXJJ_mX4T5VSG&s=0",
        "employer_website": null,
        "employer_company_type": null,
        "job_publisher": "LinkedIn",
        "job_id": "BTxJaxFHV3MAAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "Full-Stack React Developer, React TypeScript Python $160k",
        "job_apply_link": "https://www.linkedin.com/jobs/view/full-stack-react-developer-react-typescript-python-%24160k-at-developrec-3691769751",
        "job_apply_is_direct": false,
        "job_apply_quality_score": 0.5766,
        "job_description": "Full-Stack React Developer, React TypeScript Python $160k\n\nFully Remote, USA\n\nSummary: My client is a rapidly expanding AI/ML business for the Insurance space who have many deliverables for 2023 which means growth across x3 squads building customer features, developer products, data visualisation services and more.\n\nMy client has specialized in optimising efficiency for underwriters and insurance technology through their Enterprise SaaS Platform.\n\nResponsibilities:\n• Designing, developing and deploying complex data visualisation services using React, TypeScript & Python\n• Building fully scalable products and applications within big-tech entreprise and start-up environments\n• Working with end customers to manage project and development lifecycle\n• Conducting reviews of existing products or applications to evaluate their potential value for the business\n\nQualifications and Skills:\n• React, JavaScript, TypeScript, Python\n• Full-Stack experience, with a majority frontend focus using React and TypeScript\n• Data visualisation experience is ideal, but not necessary\n• Strong Computer Science educational background\n• Able to communicate technical and non-technical goals\n\nSalary and Benefits:\n• Salary: $140k - $170k+\n• Bonus - personal and company performance based\n• Executive level equity options\n• Family plan for health care and insurances\n\nFull-Stack React Developer, React TypeScript Python $160k\n\nFully Remote, USA",
        "job_is_remote": true,
        "job_posted_at_timestamp": 1692629295,
        "job_posted_at_datetime_utc": "2023-08-21T14:48:15.000Z",
        "job_city": null,
        "job_state": null,
        "job_country": "US",
        "job_latitude": 37.09024,
        "job_longitude": -95.71289,
        "job_benefits": [
            "retirement_savings",
            "health_insurance"
        ],
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=BTxJaxFHV3MAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": "2023-09-20T14:48:15.000Z",
        "job_offer_expiration_timestamp": 1695221295,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": null,
            "experience_mentioned": true,
            "experience_preferred": false
        },
        "job_required_skills": null,
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": true,
            "degree_mentioned": false,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": 140000,
        "job_max_salary": 170000,
        "job_salary_currency": "USD",
        "job_salary_period": "YEAR",
        "job_highlights": {
            "Qualifications": [
                "React, JavaScript, TypeScript, Python",
                "Full-Stack experience, with a majority frontend focus using React and TypeScript",
                "Data visualisation experience is ideal, but not necessary",
                "Strong Computer Science educational background",
                "Able to communicate technical and non-technical goals"
            ],
            "Responsibilities": [
                "Designing, developing and deploying complex data visualisation services using React, TypeScript & Python",
                "Building fully scalable products and applications within big-tech entreprise and start-up environments",
                "Working with end customers to manage project and development lifecycle",
                "Conducting reviews of existing products or applications to evaluate their potential value for the business"
            ],
            "Benefits": [
                "Salary: $140k - $170k+",
                "Bonus - personal and company performance based",
                "Executive level equity options",
                "Family plan for health care and insurances",
                "Full-Stack React Developer, React TypeScript Python $160k"
            ]
        },
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15113400",
        "job_onet_job_zone": "3"
    },
    {
        "employer_name": "Insight Global",
        "employer_logo": "https://images.squarespace-cdn.com/content/5f7f984c3ca20d1d55b276f7/1619793549819-L54X3W9Z5RD277UPNH9S/IGLogoPublic.png?content-type=image%2Fpng",
        "employer_website": "http://www.insightglobal.com",
        "employer_company_type": "Staffing",
        "job_publisher": "LinkedIn",
        "job_id": "sgoykGpsf9wAAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "React Native Developer",
        "job_apply_link": "https://www.linkedin.com/jobs/view/react-native-developer-at-insight-global-3702469261",
        "job_apply_is_direct": false,
        "job_apply_quality_score": 0.5532,
        "job_description": "Remote contract to hire role\n\nMust-haves\n\n3+ years experience with Mobile development, iOS/ Android\n\nStrong experience with React Native\n\nJavaScript experience\n\nExperience bootstrapping mobile applications\n\nMinimum 2 years of experience in Agile/Scrum.\n\nExperience in a CICD environment\n\nPlusses\n\nExperience building mobile apps independently that are available on online platforms\n\nReactJS experience\n\nGoogle Cloud\n\nDay-to-Day\n\nAn employer is looking for a React Native Developer to sit remotely. Your main responsibility will be to aid the client with enhancing their mobile e-commerce application. You will be part of a scrum methodology, building out new product offerings on the current react native, mobile application. You will meet with the business units/ stakeholders to better understand and gather requirements then work with the solutions architect to build out these applications. Additional tasks will include unit/ smoke testing, design conversation workflows, etc.",
        "job_is_remote": true,
        "job_posted_at_timestamp": 1692795501,
        "job_posted_at_datetime_utc": "2023-08-23T12:58:21.000Z",
        "job_city": null,
        "job_state": null,
        "job_country": "US",
        "job_latitude": 37.09024,
        "job_longitude": -95.71289,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=sgoykGpsf9wAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": "2023-09-22T12:58:21.000Z",
        "job_offer_expiration_timestamp": 1695387501,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": null,
            "experience_mentioned": true,
            "experience_preferred": false
        },
        "job_required_skills": null,
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": true,
            "degree_mentioned": false,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": 130000,
        "job_max_salary": 140000,
        "job_salary_currency": "USD",
        "job_salary_period": "YEAR",
        "job_highlights": {
            "Qualifications": [
                "3+ years experience with Mobile development, iOS/ Android",
                "Strong experience with React Native",
                "JavaScript experience",
                "Experience bootstrapping mobile applications",
                "Minimum 2 years of experience in Agile/Scrum",
                "Experience in a CICD environment",
                "Experience building mobile apps independently that are available on online platforms",
                "ReactJS experience"
            ],
            "Responsibilities": [
                "Your main responsibility will be to aid the client with enhancing their mobile e-commerce application",
                "You will be part of a scrum methodology, building out new product offerings on the current react native, mobile application",
                "You will meet with the business units/ stakeholders to better understand and gather requirements then work with the solutions architect to build out these applications",
                "Additional tasks will include unit/ smoke testing, design conversation workflows, etc"
            ]
        },
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15113200",
        "job_onet_job_zone": "4",
        "job_naics_code": "561311",
        "job_naics_name": "Employment Placement Agencies"
    },
    {
        "employer_name": "Upwork",
        "employer_logo": "https://image.status.io/z6aeO6kAGsAG.png",
        "employer_website": "http://www.elance.com",
        "employer_company_type": "Computer Services",
        "job_publisher": "Upwork",
        "job_id": "TKx0vnxuRF4AAAAAAAAAAA==",
        "job_employment_type": "CONTRACTOR",
        "job_title": "Full stack node.js and react developer needed",
        "job_apply_link": "https://www.upwork.com/job/Full-stack-node-and-react-developer-needed_~013c196d37c728a1d2/",
        "job_apply_is_direct": true,
        "job_apply_quality_score": 0.6816,
        "job_description": "We are looking for an expert full stack node.js and react developer to work on our time tracking app. You would start ASAP. Must have 5+ years of experience. I look forward to talking soon!",
        "job_is_remote": true,
        "job_posted_at_timestamp": 1692793057,
        "job_posted_at_datetime_utc": "2023-08-23T12:17:37.000Z",
        "job_city": null,
        "job_state": null,
        "job_country": "US",
        "job_latitude": 37.09024,
        "job_longitude": -95.71289,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=TKx0vnxuRF4AAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": null,
        "job_offer_expiration_timestamp": null,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": 60,
            "experience_mentioned": true,
            "experience_preferred": false
        },
        "job_required_skills": [
            "React",
            "Node.js",
            "JavaScript"
        ],
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": false,
            "degree_mentioned": false,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {
            "Qualifications": [
                "Must have 5+ years of experience"
            ]
        },
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15113400",
        "job_onet_job_zone": "3",
        "job_naics_code": "541511",
        "job_naics_name": "Custom Computer Programming Services"
    },
    {
        "employer_name": "Upwork",
        "employer_logo": "https://image.status.io/z6aeO6kAGsAG.png",
        "employer_website": "http://www.elance.com",
        "employer_company_type": "Computer Services",
        "job_publisher": "Upwork",
        "job_id": "zoDb3wZigp4AAAAAAAAAAA==",
        "job_employment_type": "CONTRACTOR",
        "job_title": "Full Stack React Developer Needed",
        "job_apply_link": "https://www.upwork.com/freelance-jobs/apply/Full-Stack-React-Developer-Needed_~01121ec828e7146e9a/",
        "job_apply_is_direct": true,
        "job_apply_quality_score": 0.6816,
        "job_description": "Hello!\n\nWe require an entry-level React developer with experience of at least 3 year. Ideally, the candidate must have experience in developing UI using React and CSS frameworks like Bootstrap, Tailwind or similar.\n\nPlease share links to some examples of the React projects that you've worked on along with responsibilities carried out by you.\n\nThanks.",
        "job_is_remote": true,
        "job_posted_at_timestamp": 1692724701,
        "job_posted_at_datetime_utc": "2023-08-22T17:18:21.000Z",
        "job_city": null,
        "job_state": null,
        "job_country": "US",
        "job_latitude": 37.09024,
        "job_longitude": -95.71289,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=zoDb3wZigp4AAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": null,
        "job_offer_expiration_timestamp": null,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": 36,
            "experience_mentioned": true,
            "experience_preferred": false
        },
        "job_required_skills": [
            "Web Development",
            "Web Application",
            "React",
            "JavaScript",
            "API Integration",
            "Node.js"
        ],
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": false,
            "degree_mentioned": false,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": 10,
        "job_max_salary": 20,
        "job_salary_currency": "USD",
        "job_salary_period": "HOUR",
        "job_highlights": {
            "Qualifications": [
                "We require an entry-level React developer with experience of at least 3 year",
                "Ideally, the candidate must have experience in developing UI using React and CSS frameworks like Bootstrap, Tailwind or similar",
                "Please share links to some examples of the React projects that you've worked on along with responsibilities carried out by you"
            ]
        },
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15113400",
        "job_onet_job_zone": "3",
        "job_naics_code": "541511",
        "job_naics_name": "Custom Computer Programming Services"
    },
    {
        "employer_name": "Upwork",
        "employer_logo": "https://image.status.io/z6aeO6kAGsAG.png",
        "employer_website": "http://www.elance.com",
        "employer_company_type": "Computer Services",
        "job_publisher": "Upwork",
        "job_id": "NTjDc-DW86gAAAAAAAAAAA==",
        "job_employment_type": "CONTRACTOR",
        "job_title": "Wanted - React Developer - Contract to Hire",
        "job_apply_link": "https://www.upwork.com/freelance-jobs/apply/Wanted-React-Developer_~01aa47a00108dc7266/",
        "job_apply_is_direct": true,
        "job_apply_quality_score": 0.6816,
        "job_description": "Looking for a low cost React Developer who is hungry to work on projects and get experience with a website agency.\n\nWe want to build out our web application development team,\n\none react developer at a time.\n\nThis is not for someone that has a ton of projects and is looking for top dollar. We are looking for value right now. Someone smart, low priced, and eager for an opportunity to work with an agency that can get clients and keep you busy.\n\nPlease reply with your experience in React plus your BEST hourly rate and we will assess the applicants based on price and experience.\n\nWe understand that many times price dictates skill, but we currently don't have the project load to justify paying someone a high rate for React Dev, so we are looking for someone that is very affordable and has a long term mindset.\n\nGood luck!",
        "job_is_remote": true,
        "job_posted_at_timestamp": 1692735427,
        "job_posted_at_datetime_utc": "2023-08-22T20:17:07.000Z",
        "job_city": null,
        "job_state": null,
        "job_country": "US",
        "job_latitude": 37.09024,
        "job_longitude": -95.71289,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=NTjDc-DW86gAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": null,
        "job_offer_expiration_timestamp": null,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": null,
            "experience_mentioned": true,
            "experience_preferred": true
        },
        "job_required_skills": [
            "React"
        ],
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": false,
            "degree_mentioned": false,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {},
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15113400",
        "job_onet_job_zone": "3",
        "job_naics_code": "541511",
        "job_naics_name": "Custom Computer Programming Services"
    },
    {
        "employer_name": "HonorVet Technologies",
        "employer_logo": null,
        "employer_website": null,
        "employer_company_type": null,
        "job_publisher": "ZipRecruiter",
        "job_id": "A1HiRcRx6b0AAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "React Developer",
        "job_apply_link": "https://www.ziprecruiter.com/c/HonorVet-Technologies/Job/React-Developer/-in-Bentonville,AR?jid=3534f77424990800",
        "job_apply_is_direct": true,
        "job_apply_quality_score": 0.7198,
        "job_description": "Required Skills\nsenior level developer, front end react experience, relocation to Bentonville required, cloud experience (Azure or GCP preferred), enterprise experience, ability to work independently\n\nJob Description\n\nReact Developer\n\nCTH - must be in Bentonville, AR upon start\n\nRequirements: React, Javascript, Cloud experience (Azure or GCP preferred)\n\nSenior level candidates, must be able to work as an independent contributor",
        "job_is_remote": false,
        "job_posted_at_timestamp": 1683338501,
        "job_posted_at_datetime_utc": "2023-05-06T02:01:41.000Z",
        "job_city": "Bentonville",
        "job_state": "AR",
        "job_country": "US",
        "job_latitude": 36.372356,
        "job_longitude": -94.21021,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=A1HiRcRx6b0AAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": "2023-09-22T00:00:00.000Z",
        "job_offer_expiration_timestamp": 1695340800,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": null,
            "experience_mentioned": true,
            "experience_preferred": true
        },
        "job_required_skills": null,
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": false,
            "degree_mentioned": false,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {
            "Qualifications": [
                "CTH - must be in Bentonville, AR upon start",
                "Senior level candidates, must be able to work as an independent contributor"
            ]
        },
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15113400",
        "job_onet_job_zone": "3",
        "job_occupational_categories": [
            "15-1134.00: Web Developers"
        ]
    },
    {
        "employer_name": "Global Soft Systems",
        "employer_logo": null,
        "employer_website": "http://globalsoftsystems.com",
        "employer_company_type": null,
        "job_publisher": "ZipRecruiter",
        "job_id": "cBVGXSQ90aYAAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "React Developer",
        "job_apply_link": "https://www.ziprecruiter.com/c/Global-Soft-Systems/Job/React-Developer/-in-Bentonville,AR?jid=c093dbcc41ade569",
        "job_apply_is_direct": true,
        "job_apply_quality_score": 0.7216,
        "job_description": "Role: React Developer\n\nDuration: 6+ months\n\nLocation: Dallas, Bentonville, Hoboken, Sunnyvale.\n\nOverview: Looking for front end developers who have experience in building web applications using React framework that is used to build web applications. Strong developer, no specific amount of years but has worked with react the same. Contributing to health project. Patient portal for health clinic. Upcoming appointments, schedule, manage profile, edit your personal information, add insurances. Developer would be contributing to code base by developing new features and maintaining the existing functionality that they have.\n\nRequired:\n• ReactJS\n• React Context API / useContext (React hook)\n• useReducer same concept behind Redux. Can have one or the other\n• useState\n• Typescript not JavaScript\n• Jest and react testing library important because developers write unit and integration tests. Not doing TDD. Develop feature and then write a test after. A different library is fine.\n• Experience building responsive applications\n• CSS/styling\n\nNice to have:\n• NextJS this would be a plus\n• GraphQL not mandatory but nice to have\n• Consume GraphQL APIs\n• ADA experience making the website accessible for seeing and hearing impaired. Will have to learn this if they don't have it. Could be the deciding factor in whether a candidate gets a job.\nBachelor's degree in Computer Science or related field or equivalent combination of industry-related professional experience and education.",
        "job_is_remote": false,
        "job_posted_at_timestamp": 1692387687,
        "job_posted_at_datetime_utc": "2023-08-18T19:41:27.000Z",
        "job_city": "Bentonville",
        "job_state": "AR",
        "job_country": "US",
        "job_latitude": 36.372356,
        "job_longitude": -94.21021,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=cBVGXSQ90aYAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": "2023-09-22T00:00:00.000Z",
        "job_offer_expiration_timestamp": 1695340800,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": null,
            "experience_mentioned": true,
            "experience_preferred": false
        },
        "job_required_skills": null,
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": false,
            "degree_mentioned": true,
            "degree_preferred": true,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {
            "Qualifications": [
                "Overview: Looking for front end developers who have experience in building web applications using React framework that is used to build web applications",
                "Strong developer, no specific amount of years but has worked with react the same",
                "ReactJS",
                "React Context API / use",
                "useReducer same concept behind Redux",
                "useState",
                "Typescript not JavaScript",
                "Jest and react testing library important because developers write unit and integration tests",
                "Experience building responsive applications",
                "GraphQL not mandatory but nice to have",
                "Consume GraphQL APIs",
                "ADA experience making the website accessible for seeing and hearing impaired",
                "Bachelor's degree in Computer Science or related field or equivalent combination of industry-related professional experience and education"
            ],
            "Responsibilities": [
                "Contributing to health project",
                "Upcoming appointments, schedule, manage profile, edit your personal information, add insurances",
                "Developer would be contributing to code base by developing new features and maintaining the existing functionality that they have",
                "Develop feature and then write a test after"
            ]
        },
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15113400",
        "job_onet_job_zone": "3",
        "job_occupational_categories": [
            "15-1134.00: Web Developers"
        ]
    }
];

export default tempData;